Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: handlers.StoreDataLambda
      CodeUri: C:\IdeaProjects\BlogInputLambda
      Runtime: java17
      Architectures:
        - x86_64