AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Handler for blog post input

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyLambdaFunction
      Handler: handlers.StoreDataLambda::handleRequest
      Runtime: java17
      MemorySize: 512
      CodeUri: target/BlogInputLambda-1.0-SNAPSHOT-shaded.jar
      Policies:
        - SecretsManagerReadWritePolicy:
            SecretName: prod/blogDB/dbUserPass
        - RDSConnectPolicy:
            DBInstanceIdentifier: blog-post-db
            Region: us-east-2